# GERADO PELO MATUGEN — seed: space-jet.png
foreground #e8eaed
background #0d1117
cursor     #8ab4f8
color0 #1f2329
color8 #3c4043
color1 #f28b82
color9 #f28b82
color2 #81c995
color10 #81c995
color3 #fdd663
color11 #fdd663
color4 #8ab4f8
color12 #8ab4f8
color5 #d7aefb
color13 #d7aefb
color6 #78d9ec
color14 #78d9ec
color7 #9aa0a6
color15 #e8eaed
